-- 0002_pgvector.sql — Helix memory facts as real vectors with an ANN index.
--
-- GENERATED by `python -m helix.pgvector_sql --write` (module
-- `helix/pgvector_sql.py`). tests/test_pgvector.py asserts the committed file
-- equals that output for the pinned embedder width (64), so changing
-- EMBED_DIM without regenerating here fails CI on purpose: a `vector(64)`
-- column and a 68-d embedder would otherwise fail at the first INSERT.
--
-- 0001_auth.sql is Better Auth's own schema and stays untouched; this file owns
-- only Helix tables. Applied by scripts/migrate.mjs (deploy / Vercel build) and
-- by the PGLite path in src/lib/db.ts, both keyed by basename in `_migrations`.

-- pgvector is not in the search path by default on RDS/Neon — this needs a
-- role that may create extensions, and the migration fails loudly if not.
CREATE EXTENSION IF NOT EXISTS vector;

-- One row per remembered fact. The embedding is a typed `vector(64)`, not
-- JSONB: JSONB gives you no distance operator, no index, and a seq-scan that
-- re-parses 64 floats per row per query.
CREATE TABLE IF NOT EXISTS helix_facts (
    id              TEXT PRIMARY KEY,
    key             TEXT NOT NULL,
    value           TEXT NOT NULL,
    source          TEXT NOT NULL DEFAULT 'user',
    observed_at     BIGINT NOT NULL,
    ttl_ms          BIGINT,
    embedding       vector(64) NOT NULL,
    embed_backend   TEXT NOT NULL,
    embed_dim       INTEGER NOT NULL DEFAULT 64,
    CHECK (embed_dim = 64)
);

-- Nearest-neighbour index. cosine ops because embeddings are L2-normalized in
-- helix/embeddings.py, and the score Helix reports is cosine similarity.
-- m = 16, ef_construction = 64: see pgvector_sql.py.
CREATE INDEX IF NOT EXISTS helix_facts_embedding_hnsw ON helix_facts USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Bookkeeping indexes: `recall` filters on TTL, `list_facts`/`forget` by key.
CREATE INDEX IF NOT EXISTS helix_facts_observed_at ON helix_facts(observed_at DESC);
CREATE INDEX IF NOT EXISTS helix_facts_key ON helix_facts(key);

-- Alternative ANN index — COMMENTED OUT; pick one strategy per deployment.
--
-- ivfflat (lists = 100 ~ 4*sqrt(n) for ~40k rows) builds in seconds
-- instead of minutes and is a fraction of HNSW's size, so it is the better
-- choice when the fact table is bulk-loaded and mostly read, or when the table
-- is big enough that HNSW's RAM cost (every vector is reachable through the
-- graph) dominates. It is the wrong choice here: Helix writes one row at a
-- time from a voice turn, ivfflat's centroid map goes stale as new facts
-- arrive, and recall collapses to a seq scan on a small table where most rows
-- share a cell. Switch by dropping the HNSW index and running:
--
--   DROP INDEX helix_facts_embedding_hnsw;
--   CREATE INDEX IF NOT EXISTS helix_facts_embedding_ivfflat ON helix_facts USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
--   SET ivfflat.probes = 10;   -- per-query: probes/lists is your recall dial
--
-- If facts expire and the table grows, prefer the partial variant below over
-- either full index, so dead rows stop costing query time:
--
--   DROP INDEX helix_facts_embedding_hnsw;
--   CREATE INDEX IF NOT EXISTS helix_facts_embedding_hnsw_live ON helix_facts USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)
--       WHERE ttl_ms IS NULL OR observed_at + ttl_ms >= 0;
