import type { KnowledgeDoc } from "./types";
import { AS_OF } from "./market";

const D = 86_400_000;

export const CORPUS: KnowledgeDoc[] = [
  {
    id: "R-BTC-REGIME",
    title: "BTC regime note: trend exhausted into high-vol",
    type: "research",
    ticker: "BTC",
    ts: AS_OF - 3 * D,
    body: "Bitcoin 20-day realized vol jumped above the 85th percentile after a failed break of the 50-day average. The 50/200 SMA spread compressed. Funding flipped negative on major perps. Treat the tape as high-vol, not a clean bull trend, until the 20-day vol falls back under 70%.",
  },
  {
    id: "R-BTC-ONCHAIN",
    title: "BTC on-chain: exchange inflow spike",
    type: "onchain",
    ticker: "BTC",
    ts: AS_OF - 5 * D,
    body: "Spot exchange inflow z-score exceeded 3.1 over a 4-day window, historically associated with distribution. Active addresses did not confirm a demand pulse. Evidence favors caution on adding risk rather than a squeeze.",
  },
  {
    id: "R-ETH-STAKING",
    title: "ETH staking queue and liquid staking flows",
    type: "onchain",
    ticker: "ETH",
    ts: AS_OF - 8 * D,
    body: "Net staking inflows slowed while liquid staking tokens traded at a mild discount. This is consistent with a pause in structural bid, not an unwind. Pair with funding: ETH perps remain near-flat, so leverage is not crowded long.",
  },
  {
    id: "R-SOL-MOM",
    title: "SOL momentum research: time-aware evidence",
    type: "strategy",
    ticker: "SOL",
    ts: AS_OF - 6 * D,
    body: "Solana 10/30 SMA crossover remains long as of the as-of date, but the last two impulse days coincided with volume z>3. Chronological eval: signals after the 2026-08 vol event overfit if you leak future bars. Use walk-forward, not a single in-sample Sharpe.",
  },
  {
    id: "R-NVDA-EARN",
    title: "NVDA event: guidance vs implied vol",
    type: "event",
    ticker: "NVDA",
    ts: AS_OF - 12 * D,
    body: "Post-print drift faded within five sessions. Implied vol crushed, realized vol stayed elevated relative to the sector. A covered-call overlay beats naked long on a 20-day horizon in this regime.",
  },
  {
    id: "R-AAPL-DEF",
    title: "AAPL as ballast in crypto-heavy books",
    type: "risk",
    ticker: "AAPL",
    ts: AS_OF - 15 * D,
    body: "AAPL 20-day vol sits near the lower quartile. Correlation to BTC realized 60-day is 0.18. Useful ballast when the book is 40% BTC; it does not hedge a crypto crash, it just damps portfolio vol.",
  },
  {
    id: "R-PORT-VAR",
    title: "Book construction: 40/25/15/10/10",
    type: "risk",
    ts: AS_OF - 2 * D,
    body: "Default Helix book: BTC 40, ETH 25, SOL 15, NVDA 10, AAPL 10. Historical 1-day 95% VaR is dominated by BTC residual. A −12% BTC shock with empirical betas produces mid-single-digit book loss, not 12%.",
  },
  {
    id: "R-STRAT-SMA",
    title: "SMA crossover playbook and costs",
    type: "strategy",
    ts: AS_OF - 20 * D,
    body: "Helix backtester uses 10/30 SMA, 10 bps round-trip. Crypto series still print positive Sharpe after costs in the sample, but max drawdown clusters around the high-vol window. Do not promote a checkpoint that only wins on the 2026 Q2 drift.",
  },
  {
    id: "R-ANOM-WINDOW",
    title: "Anomaly window late sample",
    type: "event",
    ts: AS_OF - 4 * D,
    body: "Days 366–377 in the research series are a designed stress: vol ×2.4, negative drift, inflow spike. Golden evals require retrieving this event when asked about dumps, funding flips, or exchange inflows. Chronological split: train before day 360.",
  },
  {
    id: "R-RAG-POLICY",
    title: "Retrieval policy: recency decay and no leakage",
    type: "research",
    ts: AS_OF - 1 * D,
    body: "Hybrid RAG: hashed 64-d embeddings + recency half-life 14 days + ticker overlap. Documents with timestamp after the query as-of date are masked. Cross-encoder rerank is a logistic probe trained on qrels, analog to LoRA rank-8 on retrieval features.",
  },
  {
    id: "R-ETH-REGIME",
    title: "ETH still trend, not high-vol",
    type: "research",
    ticker: "ETH",
    ts: AS_OF - 2 * D,
    body: "ETH 50-day holds above the 200-day. Realized vol is elevated versus AAPL but below the BTC stress band. Label: bull-trend with a watch if funding goes deeply negative.",
  },
  {
    id: "R-SOL-ONCHAIN",
    title: "SOL fees and active addresses",
    type: "onchain",
    ticker: "SOL",
    ts: AS_OF - 9 * D,
    body: "Active addresses remain in an uptrend even as price mean-reverted 8%. Fee burn is not a trading signal by itself; pair with the SMA state. No exchange-inflow analog at BTC magnitude.",
  },
  {
    id: "R-CITATION",
    title: "Groundedness contract",
    type: "research",
    ts: AS_OF - 1 * D,
    body: "Every numerical claim in a spoken answer must come from a tool: snapshot, backtest, risk, or retrieved evidence. If a tool is missing, say so. Citation correctness is scored as overlap between cited ids and retrieved ids.",
  },
  {
    id: "R-PROMOTE",
    title: "Promotion gates for retrieval checkpoints",
    type: "strategy",
    ts: AS_OF - 7 * D,
    body: "Staging → shadow → canary → production. Gates: nDCG@10 ≥ 0.72, Recall@5 ≥ 0.80, groundedness ≥ 0.85, p95 latency < 800ms, cost/query < $0.02. Shadow compares the candidate reranker against production without changing live routing.",
  },
  {
    id: "R-MCP",
    title: "MCP tool servers",
    type: "research",
    ts: AS_OF - 10 * D,
    body: "Helix exposes three MCP-style servers: market (snapshot, regime, anomalies, backtest, risk), retrieval (search, rerank), and eval (golden run, promote). propose_rebalance requires human approval; all other tools auto-run.",
  },
  {
    id: "R-BTC-STRAT",
    title: "BTC strategy research: do not fade the stress blindly",
    type: "strategy",
    ticker: "BTC",
    ts: AS_OF - 4 * D,
    body: "After the inflow spike, a naive mean-reversion fade lost money in the first 48h of the stress window. Evidence-grounded stance: wait for vol contraction, then re-enter with SMA confirmation.",
  },
  {
    id: "R-PORT-REVIEW",
    title: "Portfolio review checklist",
    type: "risk",
    ts: AS_OF - 3 * D,
    body: "Copilot review: (1) regime per sleeve (2) last anomaly (3) 95% VaR vs limit (4) BTC shock scenario (5) citations for any discretionary tilt. Structured output only — no free-text PnL.",
  },
  {
    id: "R-GOLDEN",
    title: "Golden / regression datasets",
    type: "research",
    ts: AS_OF - 6 * D,
    body: "EvalForge golden set covers regime, anomaly, backtest, risk, and research intents. Regression suite re-runs on every checkpoint. Failures become labeled feedback for the next SFT/LoRA-style reranker round.",
  },
];
