import type { Trace } from "./types";
import { AS_OF } from "./market";

const H = 3_600_000;

export const SEED_TRACES: Trace[] = [
  {
    id: "tr-10491",
    ts: AS_OF - 2 * H,
    query: "BTC regime and last inflow anomaly",
    intent: "regime",
    tools: ["get_market_snapshot", "detect_regime", "retrieve_evidence"],
    latencyMs: 412,
    tokens: 640,
    costUsd: 0.0041,
    retrievalHit: true,
    feedback: "up",
  },
  {
    id: "tr-10488",
    ts: AS_OF - 5 * H,
    query: "SOL sma backtest after the vol event",
    intent: "backtest",
    tools: ["run_backtest", "retrieve_evidence"],
    latencyMs: 388,
    tokens: 510,
    costUsd: 0.0033,
    retrievalHit: true,
  },
  {
    id: "tr-10481",
    ts: AS_OF - 9 * H,
    query: "Why did the copilot cite NVDA on a BTC question",
    intent: "research",
    tools: ["retrieve_evidence"],
    latencyMs: 290,
    tokens: 420,
    costUsd: 0.0026,
    retrievalHit: false,
    feedback: "down",
  },
  {
    id: "tr-10476",
    ts: AS_OF - 14 * H,
    query: "Book VaR and 12 percent BTC shock",
    intent: "risk",
    tools: ["estimate_risk"],
    latencyMs: 176,
    tokens: 380,
    costUsd: 0.0021,
    retrievalHit: true,
    feedback: "up",
  },
  {
    id: "tr-10470",
    ts: AS_OF - 20 * H,
    query: "ETH staking flows",
    intent: "research",
    tools: ["retrieve_evidence"],
    latencyMs: 254,
    tokens: 460,
    costUsd: 0.0029,
    retrievalHit: true,
  },
  {
    id: "tr-10461",
    ts: AS_OF - 28 * H,
    query: "Promote qlora if nDCG holds",
    intent: "eval",
    tools: ["get_eval_report", "get_checkpoint_status"],
    latencyMs: 198,
    tokens: 290,
    costUsd: 0.0018,
    retrievalHit: true,
  },
];
