apiVersion: v1
kind: Service
metadata:
  name: helix-web
  namespace: helix
  labels:
    app: helix
    component: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: helix
    component: web
